namespace Excise.Core.Text;

/// <summary>
/// PostScript glyph name → Unicode lookup, following the Adobe Glyph List (AGL)
/// convention (https://github.com/adobe-type-tools/agl-aglfn — public-domain
/// reference data, not the copyrighted font program). Used to decode a simple
/// font's <c>/Encoding &lt;&lt; /Differences [...] &gt;&gt;</c> array
/// (ISO 32000-2 §9.6.6.2) when there is no <c>/ToUnicode</c> CMap to consult
/// directly — see issue #662.
/// </summary>
/// <remarks>
/// This is deliberately a subset (~200 entries) covering StandardEncoding,
/// WinAnsiEncoding, MacRomanEncoding, and a handful of common Symbol-font
/// glyph names — the names that actually show up in real-world
/// <c>/Differences</c> arrays — not the full ~4300-entry AGL. The full AGL
/// also defines an algorithmic convention for names not in this table
/// (<c>uniXXXX</c> / <c>uXXXX[XX[XX]]</c>), which is handled separately in
/// <see cref="TextExtractor"/> before this table is consulted.
/// </remarks>
internal static class AdobeGlyphList
{
    /// <summary>
    /// Maps a PostScript glyph name to its Unicode string. Returns null if the
    /// name is not recognized (including any suffix after a "." glyph-variant
    /// separator, e.g. "A.sc" → try "A").
    /// </summary>
    public static string? ToUnicode(string glyphName)
    {
        if (string.IsNullOrEmpty(glyphName))
            return null;

        if (NameToUnicode.TryGetValue(glyphName, out var direct))
            return direct;

        // Glyph variant suffix convention, e.g. "A.sc", "one.oldstyle" — look
        // up the base name before the first '.'.
        var dot = glyphName.IndexOf('.');
        if (dot > 0 && NameToUnicode.TryGetValue(glyphName.Substring(0, dot), out var baseName))
            return baseName;

        return null;
    }

    private static readonly Dictionary<string, string> NameToUnicode = new()
    {
        // ASCII punctuation / digits / letters (StandardEncoding & WinAnsiEncoding agree here)
        ["space"] = " ",
        ["exclam"] = "!",
        ["quotedbl"] = "\"",
        ["numbersign"] = "#",
        ["dollar"] = "$",
        ["percent"] = "%",
        ["ampersand"] = "&",
        ["quotesingle"] = "'",
        ["quoteright"] = "’",
        ["parenleft"] = "(",
        ["parenright"] = ")",
        ["asterisk"] = "*",
        ["plus"] = "+",
        ["comma"] = ",",
        ["hyphen"] = "-",
        ["minus"] = "−",
        ["period"] = ".",
        ["slash"] = "/",
        ["zero"] = "0",
        ["one"] = "1",
        ["two"] = "2",
        ["three"] = "3",
        ["four"] = "4",
        ["five"] = "5",
        ["six"] = "6",
        ["seven"] = "7",
        ["eight"] = "8",
        ["nine"] = "9",
        ["colon"] = ":",
        ["semicolon"] = ";",
        ["less"] = "<",
        ["equal"] = "=",
        ["greater"] = ">",
        ["question"] = "?",
        ["at"] = "@",
        ["A"] = "A",
        ["B"] = "B",
        ["C"] = "C",
        ["D"] = "D",
        ["E"] = "E",
        ["F"] = "F",
        ["G"] = "G",
        ["H"] = "H",
        ["I"] = "I",
        ["J"] = "J",
        ["K"] = "K",
        ["L"] = "L",
        ["M"] = "M",
        ["N"] = "N",
        ["O"] = "O",
        ["P"] = "P",
        ["Q"] = "Q",
        ["R"] = "R",
        ["S"] = "S",
        ["T"] = "T",
        ["U"] = "U",
        ["V"] = "V",
        ["W"] = "W",
        ["X"] = "X",
        ["Y"] = "Y",
        ["Z"] = "Z",
        ["bracketleft"] = "[",
        ["backslash"] = "\\",
        ["bracketright"] = "]",
        ["asciicircum"] = "^",
        ["underscore"] = "_",
        ["grave"] = "`",
        ["quoteleft"] = "‘",
        ["a"] = "a",
        ["b"] = "b",
        ["c"] = "c",
        ["d"] = "d",
        ["e"] = "e",
        ["f"] = "f",
        ["g"] = "g",
        ["h"] = "h",
        ["i"] = "i",
        ["j"] = "j",
        ["k"] = "k",
        ["l"] = "l",
        ["m"] = "m",
        ["n"] = "n",
        ["o"] = "o",
        ["p"] = "p",
        ["q"] = "q",
        ["r"] = "r",
        ["s"] = "s",
        ["t"] = "t",
        ["u"] = "u",
        ["v"] = "v",
        ["w"] = "w",
        ["x"] = "x",
        ["y"] = "y",
        ["z"] = "z",
        ["braceleft"] = "{",
        ["bar"] = "|",
        ["braceright"] = "}",
        ["asciitilde"] = "~",

        // Latin-1 punctuation / letters (WinAnsiEncoding / MacRomanEncoding high range)
        ["nbspace"] = " ",
        ["exclamdown"] = "¡",
        ["cent"] = "¢",
        ["sterling"] = "£",
        ["currency"] = "¤",
        ["yen"] = "¥",
        ["brokenbar"] = "¦",
        ["section"] = "§",
        ["dieresis"] = "¨",
        ["copyright"] = "©",
        ["ordfeminine"] = "ª",
        ["guillemotleft"] = "«",
        ["logicalnot"] = "¬",
        ["registered"] = "®",
        ["macron"] = "¯",
        ["degree"] = "°",
        ["plusminus"] = "±",
        ["twosuperior"] = "²",
        ["threesuperior"] = "³",
        ["acute"] = "´",
        ["mu"] = "µ",
        ["paragraph"] = "¶",
        ["periodcentered"] = "·",
        ["cedilla"] = "¸",
        ["onesuperior"] = "¹",
        ["ordmasculine"] = "º",
        ["guillemotright"] = "»",
        ["onequarter"] = "¼",
        ["onehalf"] = "½",
        ["threequarters"] = "¾",
        ["questiondown"] = "¿",
        ["Agrave"] = "À",
        ["Aacute"] = "Á",
        ["Acircumflex"] = "Â",
        ["Atilde"] = "Ã",
        ["Adieresis"] = "Ä",
        ["Aring"] = "Å",
        ["AE"] = "Æ",
        ["Ccedilla"] = "Ç",
        ["Egrave"] = "È",
        ["Eacute"] = "É",
        ["Ecircumflex"] = "Ê",
        ["Edieresis"] = "Ë",
        ["Igrave"] = "Ì",
        ["Iacute"] = "Í",
        ["Icircumflex"] = "Î",
        ["Idieresis"] = "Ï",
        ["Eth"] = "Ð",
        ["Ntilde"] = "Ñ",
        ["Ograve"] = "Ò",
        ["Oacute"] = "Ó",
        ["Ocircumflex"] = "Ô",
        ["Otilde"] = "Õ",
        ["Odieresis"] = "Ö",
        ["multiply"] = "×",
        ["Oslash"] = "Ø",
        ["Ugrave"] = "Ù",
        ["Uacute"] = "Ú",
        ["Ucircumflex"] = "Û",
        ["Udieresis"] = "Ü",
        ["Yacute"] = "Ý",
        ["Thorn"] = "Þ",
        ["germandbls"] = "ß",
        ["agrave"] = "à",
        ["aacute"] = "á",
        ["acircumflex"] = "â",
        ["atilde"] = "ã",
        ["adieresis"] = "ä",
        ["aring"] = "å",
        ["ae"] = "æ",
        ["ccedilla"] = "ç",
        ["egrave"] = "è",
        ["eacute"] = "é",
        ["ecircumflex"] = "ê",
        ["edieresis"] = "ë",
        ["igrave"] = "ì",
        ["iacute"] = "í",
        ["icircumflex"] = "î",
        ["idieresis"] = "ï",
        ["eth"] = "ð",
        ["ntilde"] = "ñ",
        ["ograve"] = "ò",
        ["oacute"] = "ó",
        ["ocircumflex"] = "ô",
        ["otilde"] = "õ",
        ["odieresis"] = "ö",
        ["divide"] = "÷",
        ["oslash"] = "ø",
        ["ugrave"] = "ù",
        ["uacute"] = "ú",
        ["ucircumflex"] = "û",
        ["udieresis"] = "ü",
        ["yacute"] = "ý",
        ["thorn"] = "þ",
        ["ydieresis"] = "ÿ",

        // Typographic symbols (WinAnsiEncoding 128-159 range names)
        ["Euro"] = "€",
        ["quotesinglbase"] = "‚",
        ["florin"] = "ƒ",
        ["quotedblbase"] = "„",
        ["ellipsis"] = "…",
        ["dagger"] = "†",
        ["daggerdbl"] = "‡",
        ["circumflex"] = "ˆ",
        ["perthousand"] = "‰",
        ["Scaron"] = "Š",
        ["guilsinglleft"] = "‹",
        ["OE"] = "Œ",
        ["Zcaron"] = "Ž",
        ["quotedblleft"] = "“",
        ["quotedblright"] = "”",
        ["bullet"] = "•",
        ["endash"] = "–",
        ["emdash"] = "—",
        ["tilde"] = "˜",
        ["trademark"] = "™",
        ["scaron"] = "š",
        ["guilsinglright"] = "›",
        ["oe"] = "œ",
        ["zcaron"] = "ž",
        ["Ydieresis"] = "Ÿ",

        // Common ligatures
        ["fi"] = "ﬁ",
        ["fl"] = "ﬂ",

        // Symbol-font Greek letters (common in math/technical /Differences arrays)
        ["Alpha"] = "Α",
        ["Beta"] = "Β",
        ["Gamma"] = "Γ",
        ["Delta"] = "Δ",
        ["Epsilon"] = "Ε",
        ["Zeta"] = "Ζ",
        ["Eta"] = "Η",
        ["Theta"] = "Θ",
        ["Iota"] = "Ι",
        ["Kappa"] = "Κ",
        ["Lambda"] = "Λ",
        ["Mu"] = "Μ",
        ["Nu"] = "Ν",
        ["Xi"] = "Ξ",
        ["Omicron"] = "Ο",
        ["Pi"] = "Π",
        ["Rho"] = "Ρ",
        ["Sigma"] = "Σ",
        ["Tau"] = "Τ",
        ["Upsilon"] = "Υ",
        ["Phi"] = "Φ",
        ["Chi"] = "Χ",
        ["Psi"] = "Ψ",
        ["Omega"] = "Ω",
        ["alpha"] = "α",
        ["beta"] = "β",
        ["gamma"] = "γ",
        ["delta"] = "δ",
        ["epsilon"] = "ε",
        ["zeta"] = "ζ",
        ["eta"] = "η",
        ["theta"] = "θ",
        ["iota"] = "ι",
        ["kappa"] = "κ",
        ["lambda"] = "λ",
        ["nu"] = "ν",
        ["xi"] = "ξ",
        ["omicron"] = "ο",
        ["pi"] = "π",
        ["rho"] = "ρ",
        ["sigma"] = "σ",
        ["tau"] = "τ",
        ["upsilon"] = "υ",
        ["phi"] = "φ",
        ["chi"] = "χ",
        ["psi"] = "ψ",
        ["omega"] = "ω",

        // Common math symbols (Symbol-font /Differences arrays)
        ["infinity"] = "∞",
        ["summation"] = "∑",
        ["product"] = "∏",
        ["radical"] = "√",
        ["partialdiff"] = "∂",
        ["nabla"] = "∇",
        ["element"] = "∈",
        ["notelement"] = "∉",
        ["universal"] = "∀",
        ["existential"] = "∃",
        ["emptyset"] = "∅",
        ["notequal"] = "≠",
        ["lessequal"] = "≤",
        ["greaterequal"] = "≥",
        ["approxequal"] = "≈",
        ["congruent"] = "≅",
        ["arrowright"] = "→",
        ["arrowleft"] = "←",
        ["arrowup"] = "↑",
        ["arrowdown"] = "↓",
        ["arrowboth"] = "↔",
    };
}
